# Generated by Django 4.2.4 on 2023-08-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_topic_room_host_message_room_room"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.RenameField(
            model_name="room",
            old_name="room",
            new_name="topic",
        ),
    ]
